arista-eosplus/puppet-eos

- metadata.json
These changes will improve the module score (defined OS support facters in) and the tags will make this module show up in more searches.   Closes #11
> Update metadata tags and operatingsystem_support

- spec/support/shared_examples_for_types.rb
Change goes with BGP feature changes.
> Add unit test cases for yes/no and other boolean values.

- Rakefile
- spec/spec_helper.rb
Still need to do a pass through all the spec tests to ensure
compatability with upcoming rbeapi 0.3.0 release.
> Rubocop cleanup.

- lib/puppet/provider/eos_bgp_config/default.rb
- lib/puppet/type/eos_bgp_config.rb
- spec/fixtures/fixture_bgp_config.yaml
- spec/unit/puppet/provider/eos_bgp_config/default_spec.rb
- spec/unit/puppet/type/eos_bgp_config_spec.rb
Adding maximum-paths and maximum-ecmp-paths
> Feature bgp update

- lib/puppet/provider/eos_vrrp/default.rb
- lib/puppet/type/eos_vrrp.rb
- lib/puppet_x/eos/provider.rb
- spec/unit/puppet/provider/eos_bgp_config/default_spec.rb
- spec/unit/puppet/provider/eos_vrrp/default_spec.rb
- spec/unit/puppet/provider/eos_vrrp/fixture_vrrp.yaml
- spec/unit/puppet/provider/eos_vrrp/set_defaults_spec.rb
- spec/unit/puppet/type/eos_vrrp_spec.rb
Added a shared method to convert keys to strings or symbols.
Noticed eos_bgp_config test was not checking ensure in provider unit test.
> Created eos_vrrp type

- lib/puppet/provider/eos_system/default.rb
- lib/puppet/type/eos_system.rb
- spec/unit/puppet/provider/eos_system/default_spec.rb
- spec/unit/puppet/provider/eos_system/fixture_system.yaml
- spec/unit/puppet/type/eos_system_spec.rb
Adding enabling for ip_routing
> Feature system update

- lib/puppet/provider/eos_staticroute/default.rb
- spec/unit/puppet/provider/eos_staticroute/default_spec.rb
Updated route_name to name in opts for the flush.
> Adjustments for idempotency in staticroute

- lib/puppet/provider/eos_acl_entry/default.rb
- lib/puppet/provider/eos_bgp_config/default.rb
- lib/puppet/provider/eos_bgp_neighbor/default.rb
- lib/puppet/provider/eos_bgp_network/default.rb
- lib/puppet/provider/eos_command/default.rb
- lib/puppet/provider/eos_config/default.rb
- lib/puppet/provider/eos_ethernet/default.rb
- lib/puppet/provider/eos_interface/default.rb
- lib/puppet/provider/eos_ipinterface/default.rb
- lib/puppet/provider/eos_mlag/default.rb
- lib/puppet/provider/eos_mlag_interface/default.rb
- lib/puppet/provider/eos_ntp_config/default.rb
- lib/puppet/provider/eos_ntp_server/default.rb
- lib/puppet/provider/eos_portchannel/default.rb
- lib/puppet/provider/eos_routemap/default.rb
- lib/puppet/provider/eos_snmp/default.rb
- lib/puppet/provider/eos_staticroute/default.rb
- lib/puppet/provider/eos_stp_interface/default.rb
- lib/puppet/provider/eos_switchport/default.rb
- lib/puppet/provider/eos_system/default.rb
- lib/puppet/provider/eos_user/default.rb
- lib/puppet/provider/eos_varp/default.rb
- lib/puppet/provider/eos_varp_interface/default.rb
- lib/puppet/provider/eos_vlan/default.rb
- lib/puppet/provider/eos_vrrp/default.rb
- lib/puppet/provider/eos_vxlan/default.rb
- lib/puppet/provider/eos_vxlan_vlan/default.rb
- lib/puppet/provider/eos_vxlan_vtep/default.rb
Need to do more testing on the version confinement.
> Confinement update

- metadata.json
> Add requirements section to metadata

- lib/puppet/provider/eos_vlan/default.rb
- spec/unit/puppet/provider/eos_vlan/default_spec.rb
> Fixed trunk groups call in provider.

- spec/unit/puppet/provider/eos_stp_interface/default_spec.rb
> Add test cases for provider methods.

- lib/puppet/type/eos_ipinterface.rb
- lib/puppet/type/eos_portchannel.rb
- lib/puppet/type/eos_routemap.rb
- lib/puppet/type/eos_switchport.rb
- lib/puppet/type/eos_varp_interface.rb
- lib/puppet/type/eos_vlan.rb
> Ensure order of array does not affect idempotency

- guide/conf.py
- guide/installation.rst
- guide/quickstart.rst
- guide/release-notes-1.4.rst
- Update some formatting
- Suppress an unnecessary sphinx warning
- Fix minor formatting
- Update URLs to rbeapi releases and the aristanetworks-eos Forge module
> Update docs WRT puppet 2015.x agents

- lib/puppet/provider/eos_user/default.rb
Please see my #86, if the PR is ok, please merge.
> Fix password change issue for md5 and sha512 passwords

- lib/puppet/provider/eos_portchannel/default.rb
For a description see  #84 
I am not sure if my solution is the bestway to tackel this issue, but if it is the best way,
please merge
Thanks,
martin
> portchannel_convergence needs two puppet runs

- lib/puppet/type/eos_ethernet.rb
- spec/unit/puppet/type/eos_ethernet_spec.rb
add new speed types which are need for e.g the 7060 switches
> add 25gfull and 50gfull for the allowed ethernet speeds

- lib/puppet/provider/eos_managementdefaults/default.rb
- lib/puppet/type/eos_managementdefaults.rb
- spec/unit/puppet/provider/eos_managementdefaults/default_spec.rb
- spec/unit/puppet/provider/eos_managementdefaults/fixture_managementdefaults.yaml
- spec/unit/puppet/type/eos_managementdefaults_spec.rb
added support for setting the crypto in managementdefaults
> added support for setting the crypto in managementdefaults

- .rubocop.yml
- lib/puppet/provider/eos_switchconfig/default.rb
- lib/puppet/type/eos_switchconfig.rb
- spec/support/fixtures.rb
- spec/unit/puppet/provider/eos_switchconfig/default_spec.rb
- spec/unit/puppet/provider/eos_switchconfig/fixture_switchconfig.txt
minimized this PR based on previously-reviewed commits.  The previous PR had a lot of extraneous content.
> Switchconfig type & provider

- lib/puppet/provider/eos_interface/default.rb
- lib/puppet/type/eos_interface.rb
- spec/unit/puppet/provider/eos_interface/default_spec.rb
- spec/unit/puppet/provider/eos_interface/fixture_interfaces.yaml
- spec/unit/puppet/type/eos_interface_spec.rb
add support for subinterfaces
add support for loadinterval
> add support for subinterfaces/loadinterval

- lib/puppet/provider/eos_alias/default.rb
- lib/puppet/type/eos_alias.rb
- spec/unit/puppet/provider/eos_alias/default_spec.rb
- spec/unit/puppet/provider/eos_alias/fixture_alias.yaml
- spec/unit/puppet/type/eos_alias.rb
> Added eos_alias type

- Gemfile
- spec/unit/puppet/provider/eos_prefixlist/default_spec.rb
- Fix #115 failing spec test
- Make several mocks in prefixlist more specific
- Resolve some rubocop findings.
> Fix prefixlists

- metadata.json
See https://groups.google.com/forum/#!topic/puppet-users/nkRPvG4q0Oo
> Remove deprecated 'pe' from requirements

- lib/puppet/provider/eos_acl_entry/default.rb
- lib/puppet/type/eos_acl_entry.rb
- spec/unit/puppet/provider/eos_acl_entry/default_spec.rb
- spec/unit/puppet/provider/eos_acl_entry/fixture_acl_entry.yaml
- spec/unit/puppet/type/eos_acl_entry_spec.rb
See https://tickets.puppetlabs.com/browse/ARISTA-57
> Support eos_acl_entry remarks

- lib/puppet/provider/eos_config/default.rb
- lib/puppet/provider/eos_logging_host/default.rb
- lib/puppet/type/eos_config.rb
- lib/puppet/type/eos_logging_host.rb
- spec/unit/puppet/provider/eos_logging_host/default_spec.rb
- spec/unit/puppet/provider/eos_logging_host/fixture_logging.yaml
- spec/unit/puppet/type/eos_logging_host_spec.rb
eos_logging_host Closes #125.
eos_config Closes #124
> Add port, protocol, and vrf properties to eos_logging_host & eos_config idempotency
